// GENERATED by scripts/build-brand-images.mjs. Do not edit by hand.
// Intrinsic size of each partner logo, so <img> can carry width/height and the
// browser reserves the right space before the file arrives.
export const PARTNER_LOGO_SIZES: Record<string, { width: number; height: number }> = {
  "/assets/images/partners/big_brothers_big_sisters.avif": {
    "width": 357,
    "height": 160
  },
  "/assets/images/partners/burnaby_neighbourhood_house.avif": {
    "width": 453,
    "height": 160
  },
  "/assets/images/partners/burnaby_public_library.avif": {
    "width": 322,
    "height": 157
  },
  "/assets/images/partners/canada_shaws_consulting.avif": {
    "width": 186,
    "height": 160
  },
  "/assets/images/partners/capilano_university.avif": {
    "width": 259,
    "height": 160
  },
  "/assets/images/partners/enactus.avif": {
    "width": 237,
    "height": 160
  },
  "/assets/images/partners/ey.avif": {
    "width": 211,
    "height": 160
  },
  "/assets/images/partners/fraser_international_college.avif": {
    "width": 160,
    "height": 160
  },
  "/assets/images/partners/global_connect_immigration.avif": {
    "width": 179,
    "height": 160
  },
  "/assets/images/partners/newcomer_jobs_canada.avif": {
    "width": 285,
    "height": 160
  },
  "/assets/images/partners/promise_vancouver.avif": {
    "width": 160,
    "height": 160
  },
  "/assets/images/partners/rbc_foundation.avif": {
    "width": 319,
    "height": 160
  },
  "/assets/images/partners/sfu.avif": {
    "width": 558,
    "height": 132
  },
  "/assets/images/partners/surrey_libraries.avif": {
    "width": 278,
    "height": 160
  },
  "/assets/images/partners/trout_lake_community_centre.avif": {
    "width": 170,
    "height": 117
  },
  "/assets/images/partners/united_way_bc.avif": {
    "width": 384,
    "height": 160
  },
  "/assets/images/partners/vancouver_public_library.avif": {
    "width": 252,
    "height": 160
  },
  "/assets/images/partners/ymca_bc.avif": {
    "width": 169,
    "height": 160
  }
};
